/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
	id("java-library")
	id("maven-publish")
}

repositories {
	mavenLocal()
		maven {
			url = uri("https://repo.maven.apache.org/maven2/")
		}
	mavenCentral()
}

dependencies {
	testImplementation(platform("org.junit:junit-bom:5.9.2"))
	testImplementation("org.junit.jupiter:junit-jupiter:5.6.2")
}

group = "moe.rylie"
version = "1.0-SNAPSHOT"
description = "software-engineering"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<JavaCompile> {
	options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
	options.encoding = "UTF-8"
}

tasks.test {
	useJUnitPlatform()
	testLogging {
		events("passed", "skipped", "failed")
	}
}
